### ISSUE TITLE
robot back end thread never join 

### ISSUE THREAD

**Issue by vincentberenz** [open-dynamic-robot-initiative/robot_interfaces#11]
There seems to be no stop function. When the destructor is called, the thread never join and hang forever.

The following is written in the terminal:
"Action did not start on time, shutting down. Any further actions will be ignored'

Tracking a little bit what is happening, looks like destructor_was_called_ is set to true, but the thread remain stuck somewhere in the loop

`for (long int t = 0; !destructor_was_called_; t++)
`

The places it gets stuck varies on the state it was in when the destructor is called. It seems functions there are waiting for something from the front end ? But typically the front end also stops activity on exit

**Comment by vincentberenz** [comment]
@luator should I go ahead and work on this ? (want to make sure nobody else is currently doing this)

**Comment by luator** [comment]
Yes, that would be great.  As far as I know, no one looked into this yet.

**Comment by luator** [comment]
I think I know now what is happening:
When the user code that is responsible for appending actions is stopped before the backend, the backend will wait for the next action (here: https://github.com/open-dynamic-robot-initiative/robot_interfaces/blob/757d16839a13f03de6d9153e76ca1c4faf0d15eb/include/robot_interfaces/robot_backend.hpp#L183) but that action will never come, so it will be stuck there forever.

This will implicitly be fixed by #25. As a workaround for now (and to verify my assumption) you can enable action repetitions by setting a high enough value via `RobotBackend::set_max_action_repetitions()`.  This will result in the last action being repeated rather than waiting for the next one and thus should avoid the blocking on destruction (on our robots we actually set this to UINT_MAX, which is probably the reason we never saw that issue).

**Comment by luator** [comment]
Should be fixed by https://github.com/machines-in-motion/time_series/pull/6
