### ISSUE TITLE
backend does not accept infinite time wait anymore

### ISSUE THREAD

**Issue by vincentberenz** [open-dynamic-robot-initiative/robot_interfaces#50]
when running :

```c++
    // max time allowed for the robot to apply an action.
    double max_action_duration_s = std::numeric_limits<double>::infinity();

    // max time allowed for 2 successive actions
    double max_inter_action_duration_s = std::numeric_limits<double>::infinity();

    std::shared_ptr<Driver> driver_ptr = std::make_shared<Driver>(0, 1000);
    std::shared_ptr<Data> data_ptr = std::make_shared<Data>();

    Backend backend(driver_ptr,
		    data_ptr,
		    max_action_duration_s,
		    max_inter_action_duration_s);
    backend.initialize();
    
    Frontend frontend(data_ptr);
    
    Action action;

    action.values[0] = 0;
    action.values[1] = 0;
    frontend.append_desired_action(action);

    usleep(2e6);
```
this happens:

> Error: Next action was not provided in time
> Robot is shut down.
> 

which should not happen because 

```c++
   // max time allowed for the robot to apply an action.
    double max_action_duration_s = std::numeric_limits<double>::infinity();

    // max time allowed for 2 successive actions
    double max_inter_action_duration_s = std::numeric_limits<double>::infinity();
```

Note that this was working fine until recently. 

You may reproduce the issue by running this demo:

[demo on maintainer/infinite_wait_broken branch](https://github.com/open-dynamic-robot-initiative/robot_interfaces/blob/maintainer/infinite_wait_broken/demos/demo_infinite_wait.cpp)

**Comment by luator** [comment]
I'll take a look.

**Comment by luator** [comment]
I found the issue: I recently added an argument `real_time_mode` to the RobotBackend.  Instead of checking if the timeout is infinite, it uses this argument now to decide if it should wait for the next action or trigger an error if it is not provided in time.
This argument defaults to `true`, so it needs to be set to `false` explicitly if you want it to wait.  I pushed a commit to your branch doing this.  Can you verify if the behaviour is as expected now?

**Comment by vincentberenz** [comment]
I am a bit confused, the demo updated in the maintainer branch does not seem to follow the current API, as it still passes max_action_duration_s to the backend constructor:

https://github.com/open-dynamic-robot-initiative/robot_interfaces/blob/master/include/robot_interfaces/robot_backend.hpp#L51

**Comment by luator** [comment]
Oh, yes, I merged a change today:  Previously the backend was wrapping the given driver in a `MonitoredRobotDriver` internally and therefore you had to pass the timeouts to the backend.  This is not happening anymore, so if you want the monitoring, you have to wrap it yourself before passing it to the backend.  On the other hand, if you _dont_ want the monitoring (e.g. because you use simulation), you can simply pass the driver as is and don't have to specify infinite timeouts anymore.
Shall I update the maintainer branch accordingly?

**Comment by vincentberenz** [comment]
no, I get it :)

**Comment by luator** [comment]
I consider this issue to be resolved.  Please reopen if I'm wrong.
